### ISSUE TITLE
Validation: adding struct validation system

### ISSUE THREAD

**Issue by oversoul** [khalyomede/mantis#1]
Thanks for this project. (changes)

i wrote some code that would help with "validation"

the idea is to use custom attributes like this:

```
struct Post {
    title string @[validate: 'required,min:10']
}
```

and when applying the validation

```
// data map[string]Value

p := validate[Post](data) or {
    panic("validation error: ${err}")
}
// p is of type Post
```

Let me know if this is something that interests you. i can make a pull request.

**Comment by khalyomede** [comment]
Hi oversoul, great idea thank you! Thanks for taking some time sketching the draft 🙏

One question: is it possible to ensure validation rules in the @ directive are checked (at compile time)?

Followup question, maybe we could split each rules to their own directive? Something like this 

```
struct Post {
  @[required]
  @[min: '3']
  title string
  
  @[min: '1']
  views
}
```

**Comment by oversoul** [comment]
i'm not sure i understand the compile time part. this is part of validating a request. i'm not sure how that would work at compile time?

for the second question, i don't think it's possible:

1. i believe `attributes` can only be declared after the field type
2. you can't declare multiple attributes like that, but you can do:

```
title string @[required; min]
```

also something like `required` is not possible, because it's a language defined attribute. that requires you to set that field at initialization, that's why i proposed the `validate`, to specify this is for validation.

**Comment by khalyomede** [comment]
I was thinking how we can enforce having the correct type for a given rule, but this was a wrong comment since attributes are already checked by V compiler so no need to have an extra compile time my bad!

I really like the idea anyway, would you be willing to draft a PR? We'll be able to iterate from there.

Thanks so much for taking your time to this nice addition 💪

**Comment by oversoul** [comment]
I create a draft PR. #2

**Comment by khalyomede** [comment]
Great work thank you @oversoul :pray:
